"""mfs0_common.py — MFS0-E0 共享层：预注册常量 + 物理装配 + 预算账本。

TYPE:INFRA（research/ 层组装；全部元件为既有 production 原语，零母本修改。
production / G0 / D2-0 / D2-1 全程 READ_ONLY——同 D2-1 TYPE:HYBRID 先例）。

依据：外部《MAINLINE V2 — MFS0-E0 修订执行方案》（2026-09-23，34 节，
status=ADOPTED_WITH_AMENDMENTS）+ 我方《MFS0-E0方案评判_2026-09-23》
（E-1~E-12，全部 INCORPORATED）+ 四项开工裁定 R-1~R-4。

## 本轮范围（方案 §34 自限）

  READY_TO_EXECUTE_STEP_0 = YES / READY_FOR_MAIN_FACTORIAL = NO
  ⇒ 本文件只服务 Step 0 / A / B / C。Step D~H 与 hold6 属下一批，
    §31 禁跳步（Step A/B/C 未 PASS 不得进 factorial）。

## 预注册块（首次运行前冻结；每项后注出处）

  MULTIPLICATION_TIER = 2          # R-2：e→FET_e / M→FET_M 两个物理量各经
                                   # 真实器件转换再组成 gate-dependent write
                                   # quantity（theta_comparator.py:170 NMDA
                                   # 乘法门控先例，用户 2026-09-06 裁定）。
                                   # LIMITATION 见 TIER2_LIMITATION。
  M_SOURCE = "H_tau_delta"         # R-1：H_τ 的 later-occurrence 专属实例；
                                   # 禁 W→H_τ^Δ（否则 M 只是 e 的重复编码）
  TAU_E = 0.300 s                  # R-4 族冻结值；**依据已换**见 TAU_E_BASIS
  INITIAL_W = 0.90                 # R-4；NO_RUNTIME_W0_SEARCH=True
  W_METABOLIC_LEAK = OFF           # 方案 §8：本轮问"能否沉积"，不问遗忘时标
  ELIGIBILITY_AMPLITUDE_ENCODING = NO   # 方案 §4.3：e 只表达"最近发生过且
                                   # 仍在有限修改资格窗口内"，不表达强度
  ELIGIBILITY_CANONICAL_STATE = capacitor voltage   # 方案 §4.4（见 E-8）
  NEW_G0_TRAJECTORIES = 0          # 方案 §14；现有窗库存足够（见 E-11c）
  PRODUCTION = READ_ONLY           # 方案 §28

## TAU_E_BASIS —— 依据更换（我方 E-10 勘误的兑现，用户 2026-09-23 裁定）

方案 §4.2 的推导链是：「旧 eligibility 意图 300 steps × dt_G 0.001 = 0.300 s」。
**该推导不成立**：`nexus_v1/circuit/bundle.py:126` 的 `eligibility_tau = 300.0`
在实现里进入 `decay_factor = 1 - dt/eligibility_tau`（同文件 :459-460），
在 dt=0.001 下等效时间常数为 **300 秒**，不是 0.3 秒——差 1000×。该常量的
注释自称 "(steps)"，是 dt=1.0 旧约定的遗留（我方评判 E-10；同族地雷见
`compensation.py` 的全部 τ 注释）。

因此本轮**不继承**该常量，`TAU_E = 0.300 s` 改由两条独立依据支撑：

  (a) BIO 时标：突触前残余 Ca²⁺ / 短时程易化的衰减在亚秒量级
      REF: Zucker & Regehr 2002, Annu Rev Physiol 64:355（项目内既有引用链：
      `tss/relations/history_kernel.py` Q1 同一文献；
      `nexus_v1/components/compensation.py:210+` CalciumRateIntegrator 同源
      钙池）。0.300 s 落在该量级内。
  (b) STRUCT 约束（决定性的一条）：资格窗必须**短于**它所标记的关系发生
      自身的衰减窗，否则 NC3（TIMING CONTROL 要求 e_W(t_Δ)≈0）在合法
      occurrence 库存内无法构造。项目内两个相邻时标：
        τ₂   = 0.456 s  （D2-1 RelationCell 实测 tau_decay2_s）
        τ_h  = 0.600 s  （H_τ 冻结值，history_kernel.py Q3）
      取 τ_e = 0.300 s < τ₂ < τ_h，并使 e 的可测尾长 ~3τ_e = 0.9 s
      与现有 site23 窗间距同量级（见 d21 site23_occurrence_manifest.csv）。

数值 0.300 与旧常量的数字 300 相同纯属巧合，语义无关——本文件不 import
bundle 的任何 step-era 常量（机器级兑现：见 `assert_no_step_era_import`）。

## WRITE_POLARITY —— 执行方决定（方案未指定，须诚实登记）

`Memristor.apply_dw` 的边界是 w∈[w_min, w_max] = [0.0, 1.0]
（`semiconductor.py:246-265`）。R-4 冻结 w₀=0.90 ⇒ **向上写只剩 0.10 余量，
向下写有 0.90 余量**。new-component skill 与
`project_memristor_saturation_edge_bug` 均记录了"w 高位撞 w_max 钳位
→ 假性效应"的历史教训。

故预注册 `WRITE_POLARITY = DEPLETION`（dw < 0），由
`Memristor.update(current, pre_trace=0.0, post_trace=POST_TRACE_UNIT)`
实现：dw = 0.5·I_write·(0 − 1) = −0.5·I_write。

  - pre/post trace 在此**只承担极性与标度**，是 API 常数不是物理量——
    诚实登记为实现选择（乘法的物理性全部由 TIER-2 双 FET 承担）。
  - 灵敏度不受损：ΔG/G = 9.9·Δw/R，w₀=0.90 处 R=1.09，向下写 Δw=−0.01
    仅使 R→1.189（灵敏度变化 <10%），仍远优于 LIM-RPREC 的 w≈0.109 工作点。

## TIER2_LIMITATION（R-2 强制登记）

  two factors are generated by physical devices, but final factor
  composition is not a fully self-consistent series-node analog solution.

即：`FET_e.conduct(e) * FET_M.conduct(M)` 的两个因子各由真实 MOSFET 产生、
任一阈下由 DEG-019 硬截零（负例是精确 0），但二者相乘在 Python 层仍是
`a * b`，**没有解串联节点的 KCL/负载线**（项目内唯一做到档 3 的是
`research/A8_state_audit/rail_latch.py:13-21`）。本轮不得宣称
`fully emergent analog multiplication`。

## 两条路径的独立性（R-1 硬要求，机器级）

  Past  W → build_phase_drive([relation port]) → tin_e  → bundle_e → C_e → e
  Later Δ → build_phase_drive([site23 window]) → adapter → gate   → H_τ^Δ → M

两条链不共享任何对象、不共享输入端口、不共享地址父节点。
`assert_paths_independent()` 做对象级 id 检查（禁 W→H_τ^Δ）。

## 阈值截零的两个不同窗口（我方 E-8 同族，必须分别报告）

  "e 存在窗"    = {t : e(t) > EPSILON_NUM}          ← M2 判据（canonical
                                                     读出=膜电压，非 activation）
  "写入可达窗"  = {t : FET_e.conduct(e(t)) > 0}     ← Step D 选 NEAR 的真实约束

二者不等价：e 在 RC 意义上长期非零，但低于 θ_FET=0.3 时写电流被硬截零。
Posterior-0 Step A 正是栽在"存在≠可读"这一面上（膜 τ=500 步 vs activation
τ=6.4 步，差 78×）。Step A 必须同时输出两个窗。
"""
from __future__ import annotations

import json
import math
import os
import sys
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Sequence, Tuple

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.abspath(os.path.join(_HERE, '..', '..'))
_D21 = os.path.abspath(os.path.join(_HERE, '..', 'd2_recursive_v1'))
_D20 = os.path.abspath(os.path.join(_HERE, '..', 'd2_relation_v0'))
for _p in (_ROOT, _D20, _D21, _HERE):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from d21_common import (  # noqa: E402
    DATA as D21_DATA, load_relation_ports, load_site23_windows,
    relation2_address)
from d2_common import DT_G  # noqa: E402
from nexus_v1.circuit.bundle import BundleConfig, SynapticBundle  # noqa: E402
from nexus_v1.components.neuron import Neuron, NeuronConfig  # noqa: E402
from nexus_v1.components.semiconductor import MOSFET  # noqa: E402
from nexus_v1.components.structural_address import (  # noqa: E402
    AddressRegistry, DOMAIN_RELATION_PREC)
from tss.adapters.relation_replay_adapter import build_phase_drive  # noqa: E402
from tss.relations.entry_gate import PhysicalEntryGate  # noqa: E402
from tss.relations.history_kernel import PhysicalHistoryKernel  # noqa: E402
from tss.relations.relation_event_adapter import (  # noqa: E402
    RelationEventAdapter, RelationInputNeuron,
    make_relation_transducer_bundle)

DATA = os.path.join(_HERE, 'data')

# ─────────────────────────────────────────────────────────────────────
# 预注册冻结常量（provenance 见模块 docstring；首次运行前冻结）
# ─────────────────────────────────────────────────────────────────────

MULTIPLICATION_TIER = 2
M_SOURCE = "H_tau_delta"
ELIGIBILITY_AMPLITUDE_ENCODING = False
ELIGIBILITY_CANONICAL_STATE = "capacitor_voltage"
W_METABOLIC_LEAK = False
NEW_G0_TRAJECTORIES = 0
PRODUCTION_MODE = "READ_ONLY"

# e 载体（τ_e = R_e·C_e = 0.300 s，依据见 TAU_E_BASIS）
TAU_E = 0.300
C_E = 0.1              # 同 D2-1 RelationCell 电容（recursive_physical_impl.py:93）
R_E = TAU_E / C_E      # = 3.0
TAU_E_TOLERANCE = 0.05  # ±5%：RC 数值积分误差量级（Capacitor.leak 为精确
                        # exp(-dt/RC)，容差留给拟合窗选择与准稳态偏差）

# M 载体（H_τ 冻结参数原样复用，零重标定）
TAU_M = 0.600          # history_kernel._DEFAULT_R_LEAK × _DEFAULT_CAPACITANCE

# 写入
INITIAL_W = 0.90       # R-4，NO_RUNTIME_W0_SEARCH
NO_RUNTIME_W0_SEARCH = True
WRITE_POLARITY = "DEPLETION"   # dw < 0，依据见 WRITE_POLARITY 节
POST_TRACE_UNIT = 1.0          # 极性/标度常数（非物理量，诚实登记）
FET_V_THRESHOLD = 0.3  # MOSFET 原语默认（semiconductor.py:130）；同
                       # entry_gate θ_g / theta_comparator 用法，零自由参数
FET_GM = 1.0           # MOSFET 原语默认；单位跨导，无隐藏放大

# 数值地板（方案 §18 优先级：deterministic replay floor → sham-repeat →
# numeric precision。本系统 replay 逐位一致 ⇒ ε_replay = 0 ⇒ 取数值精度地板，
# 同 Posterior-0 EPSILON_NUM 先例）
EPSILON_NUM = 1e-6
EPSILON_E = EPSILON_NUM
EPSILON_M = EPSILON_NUM
EPSILON_Z = EPSILON_NUM        # |Δw_near| 下限（Step C 若解析可达量更紧则收紧）
RETENTION_W_MIN = 0.99         # W_METABOLIC_LEAK=OFF ⇒ 理论 1.0；留数值余量

# 素材选择（复用已录窗，new_g0 = 0）
W_RELATION_TRAJ = "cal_C3_m"   # D2-1 主 parent（d21_common RHO_MAIN_TRAJ）
DELTA_S23_TID_STEPB = "s23_lag"  # Step B 仅证明 Δ→M 可行；NEAR/TC 的正式
                                 # 选择在 Step D（本轮不做）
T_TOTAL_STEPA = 12000          # 含零驱动垫尾，观测 e 的完整衰减
                               # （实测 e 末次越 ε 在 8473 步，余量充足）
T_TOTAL_STEPB = 14000          # 首跑 12000 不足：M 在 t_peak=4162 起以
                               # τ_M=0.6 s 衰减，降到 ε_M=1e-6 需
                               # ln(0.998/1e-6)·600 = 8288 步 ⇒ t ≈ 12450。
                               # 这是**观测窗**长度，不是物理参数（τ_M 冻结
                               # 未动，w0/amplitude/timing 均未动）；首跑与
                               # 重跑双双登记 attempted_run（方案 §25）。

BUDGET_CAPS = {"new_g0_trajectories": 0,
               "eligibility_calibration": 6,
               "modulation_calibration": 6,
               "persistent_baseline": 6,
               "timing_points": 4,
               "factorial_sets": 4,
               "timing_controls": 3,
               "state_interventions": 4,
               "path_blocks": 3,
               "heldout": 6}
LEDGER_PATH = os.path.join(DATA, 'budget_ledger.json')

TIER2_LIMITATION = (
    "two factors are generated by physical devices, but final factor "
    "composition is not a fully self-consistent series-node analog solution")


# ─────────────────────────────────────────────────────────────────────
# 纪律守卫（机器级兑现，非注释承诺）
# ─────────────────────────────────────────────────────────────────────

def assert_no_step_era_import() -> None:
    """守卫 TAU_E_BASIS：本轮不得继承 bundle 的 step-era eligibility/DA 常量。

    方案 §26 + 我方 E-10：`bundle.py` 的 eligibility_tau=300 / da_ema_tau=5000
    是步制且在 dt=0.001 下等效 300 s / 5000 s。本模块只 import BundleConfig /
    SynapticBundle（结构），不读这两个常量。
    """
    import nexus_v1.circuit.bundle as _b
    src = os.path.abspath(_b.__file__)
    with open(os.path.join(_HERE, 'mfs0_common.py'), encoding='utf-8') as f:
        text = f.read()
    for banned in ('eligibility_tau', 'da_ema_tau', 'lambda_metabolic'):
        # 只允许出现在 docstring 的勘误说明里，不得出现在 import/赋值位置
        for line in text.splitlines():
            s = line.strip()
            if banned in s and (s.startswith('from ') or s.startswith('import ')
                                or s.startswith(f'{banned} =')):
                raise AssertionError(
                    f"STEP_ERA_CONSTANT_LEAK: {banned} 不得进入 MFS0"
                    f"（方案 §26 / 评判 E-10；源 {src}）")


def assert_paths_independent(elig, modu) -> None:
    """守卫 R-1：Past→e 与 Later→M 两条链对象级不相交（禁 W→H_τ^Δ）。"""
    e_objs = {id(elig.tin), id(elig.bundle), id(elig.cell)}
    m_objs = {id(modu.adapter), id(modu.adapter.input_neuron),
              id(modu.adapter.collector), id(modu.adapter.bundle),
              id(modu.gate), id(modu.kernel)}
    overlap = e_objs & m_objs
    if overlap:
        raise AssertionError(
            f"PATH_INDEPENDENCE_VIOLATION: e 链与 M 链共享对象 {overlap}"
            "（R-1：M 可能只是 e 的重复编码）")


# ─────────────────────────────────────────────────────────────────────
# Step A 装配：Past(χ_ρ^(1)) → e
# ─────────────────────────────────────────────────────────────────────

@dataclass
class EligibilityParts:
    """e 链的物理对象（全部既有 production 原语）。"""
    tin: RelationInputNeuron
    bundle: SynapticBundle
    cell: Neuron

    @property
    def e(self) -> float:
        """canonical eligibility 读出 = 电容电压（方案 §4.4；非 activation）。"""
        return self.cell._membrane.voltage      # DIAGNOSTIC_READ（只读）

    @property
    def e_activation(self) -> float:
        """DIAGNOSTIC_ONLY：过 MOSFET 后的读出，阈下硬截零（DEG-019）。"""
        return self.cell.activation


def build_eligibility(ident: str = "mfs0_e") -> EligibilityParts:
    """χ_ρ^(1) → I_e → C_e 的物理装配。

    Q1 BIO: 突触标记 / 残余 Ca²⁺——一次关系发生在突触留下有限时长的
            "可修改资格"（REF: Zucker & Regehr 2002；项目内同引用链见
            history_kernel.py Q1 与 compensation.py CalciumRateIntegrator）。
    Q2 PHYS: RelationOccurrencePortV1 → build_phase_drive → RelationInputNeuron
            （HC-009 换能先例）→ frozen SynapticBundle → Neuron(_membrane
            = Capacitor)。Sources/Targets 全是真实 Neuron 对象，无变量注入。
    Q3 PARAM: C_E/R_E 见 TAU_E_BASIS；换能束参数继承
            make_relation_transducer_bundle（w=0.3 frozen / gain=1.0 /
            physical_seed=91000，relation_event_adapter.py Q3）。
    """
    tin = RelationInputNeuron(ident)
    cell = Neuron(NeuronConfig(
        neuron_id=f"mfs0_eligibility_cap_{ident}",
        capacitance=C_E, r_leak=R_E,       # τ_e = R·C = 0.300 s
        inertia=0.0, vdd=2.0, r_supply=0.01, spiking=False))
    bundle = make_relation_transducer_bundle(ident, tin, cell)
    return EligibilityParts(tin, bundle, cell)


def step_eligibility(p: EligibilityParts, theta: float,
                     dt: float = DT_G) -> float:
    """推进一步，返回 canonical e = V_{C_e}。theta = build_phase_drive 的 ϑ。"""
    p.tin.step(theta, dt)
    currents = p.bundle.propagate()
    p.cell.step(currents[0] if currents else 0.0, dt)
    return p.e


# ─────────────────────────────────────────────────────────────────────
# Step B 装配：Later(Δ) → H_τ^Δ → M
# ─────────────────────────────────────────────────────────────────────

@dataclass
class ModulationParts:
    """M 链的物理对象（H_τ 的 later-occurrence 专属实例）。"""
    adapter: RelationEventAdapter
    gate: PhysicalEntryGate
    kernel: PhysicalHistoryKernel
    _m: float = field(default=0.0, init=False)

    @property
    def M(self) -> float:
        """M(t) = h^Δ(t)，H_τ^Δ 的充电前历史读出（严格先序）。"""
        return self._m


def build_modulation(ident: str = "mfs0_m_delta") -> ModulationParts:
    """Δ → 换能 → spiking collector → E^↑ → H_τ^Δ → M 的物理装配。

    Q1 BIO: later occurrence 在局部留下的进入历史痕（同 H_τ 的 Q1：
            突触前残余 Ca²⁺ / 短时程易化）。**无 valence**——不表示
            reward/punishment/success/failure（方案 §5/§6）。
    Q2 PHYS: RelationEventAdapter（换能→frozen 束→spiking collector→
            CollectorBoundaryPort，HC-009 拓扑 A）→ PhysicalEntryGate
            （b^↑，每枚 spike 刷新 + Zener 钳位）→ PhysicalHistoryKernel
            （τ_h=0.6 s RC 历史池）。三件套默认参数零改动。
    Q3 PARAM: 全部继承既有冻结值（adapter Q3 / entry_gate Q3 / history_kernel
            Q3），本轮零新参数。τ_M = τ_h = 0.600 s。

    R-1 独立性：本实例的输入端口只接 Δ 的 site23 窗，地址父节点为 site23
    生成元，与 W 的 relation port 无任何共享对象（assert_paths_independent）。
    """
    reg = AddressRegistry()
    _rho2, _rho, addr_c = relation2_address()
    # 谱系父 = (site23 生成元, site23 生成元)：本实例完全源自 Δ 侧，
    # 不含 W/ρ 的地址——R-1 "独立地址" 的结构兑现。
    adapter = RelationEventAdapter(reg, addr_c, addr_c, ident)
    gate = PhysicalEntryGate(generator_address=adapter.generator_address)
    kernel = PhysicalHistoryKernel(generator_address=gate.generator_address)
    return ModulationParts(adapter, gate, kernel)


def step_modulation(p: ModulationParts, theta: float,
                    dt: float = DT_G) -> float:
    """推进一步，返回 M(t)。theta = Δ 侧 build_phase_drive 的 ϑ。"""
    spike = p.adapter.step(theta, dt)
    b_up = p.gate.step(spike, dt)
    p._m = p.kernel.step(b_up, dt)
    return p._m


# ─────────────────────────────────────────────────────────────────────
# 写入装配：TIER-2 双 FET 门控写电流 → Memristor.w
# ─────────────────────────────────────────────────────────────────────

@dataclass
class WriteGate:
    """TIER-2 乘法门 + 持久载体 w。

    Q1 BIO: 突触标记（e）与神经调质（M）的符合门控可塑性——两者同时在场
            才发生持久权重改变（三因子可塑性的物理形态）。
    Q2 PHYS: e→FET_e / M→FET_M 两个真实 MOSFET，各自阈下硬截零（DEG-019）；
            乘积作为 write current 进入 Memristor.update（原语中唯一的
            "写电流→w"入口，semiconductor.py:277-280 Strukov 型）。
            范式先例：theta_comparator.py:170 NMDA 乘法门控（用户 2026-09-06
            裁定"比较完全由物理结构承担"）。
    Q3 PARAM: FET 阈值/跨导取 MOSFET 原语默认（0.3 / 1.0），零自由参数；
            w₀=0.90 由 R-4 冻结；极性见 WRITE_POLARITY。

    LIMITATION（R-2 强制）：见 TIER2_LIMITATION——两个因子由器件产生，但
    合成不是自洽串联节点解。
    """
    fet_e: MOSFET
    fet_m: MOSFET
    bundle: SynapticBundle          # 承载 memristor 并提供未来读出通路
    src: RelationInputNeuron
    dst: Neuron
    i_write_last: float = field(default=0.0, init=False)

    @property
    def mem(self):
        """被写入/读出的同一个 Memristor（bundle 内第 0 条突触）。"""
        return self.bundle._memristors[0][0]

    @property
    def w(self) -> float:
        return self.mem.w

    def write(self, e: float, m: float) -> float:
        """一步写入：I_write = FET_e(e)·FET_M(M) → Memristor.update。

        任一因子阈下 ⇒ 该 FET conduct 精确为 0 ⇒ I_write=0 ⇒ dw=0
        （负例是精确零，非近似——DEG-019 硬截零）。
        """
        i_e = self.fet_e.conduct(e)
        i_m = self.fet_m.conduct(m)
        i_write = i_e * i_m
        self.i_write_last = i_write
        # WRITE_POLARITY=DEPLETION：dw = 0.5·I·(pre−post) = −0.5·I
        self.mem.update(current=i_write, pre_trace=0.0,
                        post_trace=POST_TRACE_UNIT)
        return i_write


def build_write_gate(ident: str = "mfs0_w") -> WriteGate:
    """装配写入门 + 持久载体。

    w₀ 显式设定为 INITIAL_W：`bundle.py:229-235` 会按 crc32(bundle_id:i:j)
    对 initial_weight 施加 ±25% 确定性扰动（多突触对称性打破用），在单突触
    场景无意义且会使实际 w₀ ≠ R-4 冻结值。显式赋值是
    NO_RUNTIME_W0_SEARCH 的兑现，不是运行时寻优。
    """
    src = RelationInputNeuron(f"{ident}_q")
    dst = Neuron(NeuronConfig(
        neuron_id=f"mfs0_readout_{ident}",
        capacitance=C_E, r_leak=R_E,
        inertia=0.0, vdd=2.0, r_supply=0.01, spiking=False))
    bundle = SynapticBundle(
        config=BundleConfig(
            bundle_id=f"mfs0_persist_{ident}",
            learning_rule="frozen",      # 不走 bundle.learn()（方案 §7）
            initial_weight=INITIAL_W,
            weight_max=1.0, weight_min=0.0,
            synapse_gain=1.0,
            bundle_role="feedforward",
            physical_seed=91000),        # 同 adapter 共参（S0-bX1 纪律）
        sources=[src], targets=[dst])
    bundle._memristors[0][0].w = INITIAL_W        # 见 docstring
    bundle._memristors[0][0]._w_initial = INITIAL_W
    return WriteGate(MOSFET(v_threshold=FET_V_THRESHOLD, gm=FET_GM),
                     MOSFET(v_threshold=FET_V_THRESHOLD, gm=FET_GM),
                     bundle, src, dst)


# ─────────────────────────────────────────────────────────────────────
# 分析原语
# ─────────────────────────────────────────────────────────────────────

def fit_tau(vs: Sequence[float], k0: int, dt: float = DT_G,
            floor: float = EPSILON_NUM) -> float:
    """对自由衰减段做 ln 线性拟合，返回实测 τ（秒）。

    只取 k0 之后、值仍高于 floor 的单调下降段——RC 自由衰减的精确指数
    （Capacitor.leak）保证 ln V 对 t 严格线性。
    """
    ks, ys = [], []
    for k in range(k0, len(vs)):
        v = vs[k]
        if v <= floor:
            break
        if ks and v > vs[ks[-1]]:
            break
        ks.append(k)
        ys.append(math.log(v))
    if len(ks) < 3:
        return float('nan')
    n = len(ks)
    mx = sum(ks) / n
    my = sum(ys) / n
    num = sum((ks[i] - mx) * (ys[i] - my) for i in range(n))
    den = sum((ks[i] - mx) ** 2 for i in range(n))
    slope = num / den if den else float('nan')
    return -1.0 / (slope / dt) if slope else float('nan')


def last_above(vs: Sequence[float], thr: float) -> int:
    """最后一个 > thr 的步号；全程不超过返回 -1。"""
    for k in range(len(vs) - 1, -1, -1):
        if vs[k] > thr:
            return k
    return -1


def window_above(vs: Sequence[float], thr: float) -> Tuple[int, int]:
    """[首个 > thr, 最后一个 > thr]；不存在返回 (-1,-1)。"""
    first = -1
    for k, v in enumerate(vs):
        if v > thr:
            first = k
            break
    return (first, last_above(vs, thr))


def conductance(w: float, r_min: float = 0.1, r_max: float = 10.0) -> float:
    """G(w) = 1/(r_min + (r_max−r_min)(1−w))，与 Memristor 原语同式。"""
    return 1.0 / max(r_min + (r_max - r_min) * (1.0 - w), r_min)


# ─────────────────────────────────────────────────────────────────────
# 素材加载（复用已录窗，new_g0 = 0）
# ─────────────────────────────────────────────────────────────────────

def w_relation_port():
    """W 的 χ_ρ^(1) typed 端口（RelationOccurrencePortV1，只读 D2-1 产物）。"""
    return load_relation_ports()[W_RELATION_TRAJ]


def delta_windows(tid: str = DELTA_S23_TID_STEPB):
    """Δ 的 site23 occurrence 窗（只读 D2-1 产物）。"""
    return list(load_site23_windows()[tid])


def drive_from_ports(ports: Sequence, t_total: int):
    """typed 端口 → 逐步 ϑ 驱动序列（唯一合法驱动展开，无幅值 DOF）。"""
    return build_phase_drive(t_total, DT_G, ports)


# ─────────────────────────────────────────────────────────────────────
# 预算账本（方案 §25；口径同 Posterior-0 ledger 先例）
# ─────────────────────────────────────────────────────────────────────

def ledger_init() -> dict:
    os.makedirs(DATA, exist_ok=True)
    if os.path.exists(LEDGER_PATH):
        with open(LEDGER_PATH, encoding='utf-8') as f:
            return json.load(f)
    led = {"caps": BUDGET_CAPS,
           "counting_rules": {
               "attempted_run": "error/aborted/duplicate/unreachable/support "
                                "failure executions are still logged "
                                "(plan §25)",
               "new_g0_trajectories": "frozen at 0 — MFS0 reuses the existing "
                                      "G0/site23 window inventory (plan §14; "
                                      "critique E-11c)"},
           "entries": []}
    _ledger_write(led)
    return led


def _ledger_write(led: dict) -> None:
    with open(LEDGER_PATH, 'w', encoding='utf-8', newline='\n') as f:
        json.dump(led, f, indent=1, ensure_ascii=False)


def ledger_add(category: str, item: str, note: str = "",
               attempted: bool = False) -> dict:
    """登记一笔预算消费。幂等（确定性重放同一评估不重复计费）。"""
    led = ledger_init()
    if any(e["category"] == category and e["item"] == item
           for e in led["entries"]):
        return led
    led["entries"].append({"category": category, "item": item,
                           "note": note, "attempted_only": attempted})
    used = sum(1 for e in led["entries"]
               if e["category"] == category and not e["attempted_only"])
    cap = led["caps"].get(category)
    if cap is not None and used > cap:
        raise RuntimeError(
            f"COMPUTE_BUDGET 超限：{category} used={used} > cap={cap}"
            "（方案 §25/§30）")
    _ledger_write(led)
    return led


def write_json(name: str, obj) -> str:
    os.makedirs(DATA, exist_ok=True)
    path = os.path.join(DATA, name)
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        json.dump(obj, f, indent=1, ensure_ascii=False)
    return path
